### PR TITLE
Apparently this is how you favicon these days

### PR DESCRIPTION
**Pull request by blha303**
For #2

### CODE REVIEW

**Comment by prplz** [comment]
I was thinking maybe just use her face instead so it actually looks like something at 16x16

**Comment by blha303** [comment]
fix'd

**Comment by blha303** [comment]
waitwaitwait

**Comment by blha303** [comment]
OK, ready

**Comment by blha303** [comment]
Oh wait, I have to rebase on the meta tag commit >_<

**Comment by blha303** [comment]
OK, i'll rebase the changes and make a new PR

**Pull request closed without merging**
